title: SLSA
description: Security framework to ensure software supply chain integrity
logo: /images/icons/android-chrome-512x512.png
copyright_html: Copyright 2021 The Linux Foundation<br>under the terms of the <a href="https://github.com/slsa-framework/slsa/blob/main/LICENSE">Apache License 2.0</a>
repository: slsa-framework/slsa
collections:
  posts:
    layout: post
    output: true
    permalink: /blog/:year/:month/:title
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor/bundle
goatcounter:
  endpoint: https://slsa.goatcounter.com/count
theme: minima
permalink: :path/:basename
markdown: CommonMarkGhPages
commonmark:
  # UNSAFE needed to support raw HTML
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["autolink", "strikethrough", "table", "tagfilter"]
titles_from_headings:
  strip_title: true
plugins:
  - jekyll-commonmark-ghpages
  - jekyll-sitemap
  - jekyll-seo-tag
  # Mandatory GitHub Pages plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
# WARNING: Remember to update _data/nav.yml as well.
spec_versions: ['v0.1']
current_spec_version: "v0.1"
provenance_versions: ['v0.1', "v0.2"]
current_provenance_version: "v0.2"
relative_links:
  collections: true
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "spec"
    values:
      layout: "specifications"
  - scope:
      path: "_posts"
    values:
      type: posts
  - scope:
      path: ""
    values:
      # Set the Social image icon
      image: /images/icons/android-chrome-512x512.png
