name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab.

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout the repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Build the SLSA website from `docs/` directory
        uses: actions/jekyll-build-pages@058068233b22675635bdf8dfa178d6ae77f12694 # v1.0.8
        with:
            source: ./docs
      - name: Upload build artifacts for deploying
        uses: actions/upload-pages-artifact@84bb4cd4b733d5c320c9c9cfbc354937524f4d64 # v1.0.10
  
  deploy:
    permissions:
      pages: write
      id-token: write # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@12ab2b16cf43a7a061fe99da74b6f8f11fb77f5b # v2.0.3
