name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows to run this workflow manually from the Actions tab.

permissions:
  contents: read
  pages: write
  id-token: write # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Setup pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6
      - name: Build
        uses: actions/jekyll-build-pages@0143c158f4fa0c5dcd99499a5d00859d79f70b0e # v1.0.7
        with:
            source: ./docs
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@64bcae551a7b18bcb9a09042ddf1960979799187 # v1.0.8
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Website
        id: deployment
        uses: actions/deploy-pages@b580d214b4e13b2a70d0e04376a86ed862ebb558 # v2.0.1