name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
    - name: Setup Node
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
    - run: ./lint.sh
