name: Lint
on: [workflow_dispatch, pull_request]
permissions: read-all
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Setup Node
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
    - run: npm ci --ignore-scripts
    - run: npm run lint --silent
    - run: ./lint.sh
